# In-Game Map Editor by Junior_Djjr - MixMods.com.br

[Settings]
MouseMoveSensMult = 2.0
MouseRotateSensMult = 60.0
MouseSensDivButton = 10.0
AutoSetGroundOffset = 1

[Project]
# File path to load/save.
Path = modloader\In-Game Map Editor\test.ipl

# If set, when saving, it uses this path instead of "Path". Otherwise, "Path" is used.
SavePath = modloader\In-Game Map Editor\test.ipl

# Always load .ipl when enabling the mod.
LoadOnEnable = 1

# Always save .ipl, as "_autosave" file name, every time before a new object is created.
AutoSave = 1

# Always save .ipl when disabling the mod.
SaveOnDisable = 0

# X Y Z coord to teleport CJ when enabling the mod
TeleportOnEnable =

# Teleport just one time per gameplay.
TeleportOnEnableOnce = 1

# I recommend this to find model IDs: https://dev.prineside.com/en/gtasa_samp_model_id/
# You can press the number on alpha keyboard to load, and hold Ctrl to save current model to .ini.
# You can hold TAB to show the list in-game.
# Tip: You can make different lists in this same file, use # to disable one and enable another, when you press the key is always updated in realtime without needing to restart the game.

[StoredModels]
Key1 = 
Key2 = 
Key3 = 
Key4 = 
Key5 = 
Key6 = 
Key7 = 
Key8 = 
Key9 = 
Key0 = 


