[Features]
QuickTeleport = true
SpawnAircraftInAir = false
SpawnWithTunes = false
TeleportMarker = false

[Menu]
LastUpdateChecked = 5

[Window]
CurrentPage = 4
PosX = 200.0
PosY = 151.0
SizeX = 480.0
SizeY = 897.0
