;ragdoll.ini
;ragdoll mod for gta:sa
; by Ryosuke839
;
[RAGDOLL]
Gravity=4.9
HumanDensity=985.0
AtomoDensity=1.5
WaterDensity=1000.0
BulletForce=50.0
ExplosionForce=100.0
VelocityLim=50.0
PhysicsLoop=4
StepLength=0.04
FreezeCount=50
VelocityRes=0.5
Friction=1500.0
Restitute=0.2
MultiThread=0
DamageMult=0.01
Detachable=1
DetachLimit=10.0
BleedTime=750
