; Soundize by Junior_Djjr - MixMods.com.br - Patreon.com/c/djjr

[Settings]
GlobalVolume = 1.0
GlobalReverbIntensity = 1.5
FmodLogo = 1     ; Projects using FMOD Studio must include an in-app credit line and the FMOD logo.
ServerMinimizedToSystemTray = 1   ; If set to "1", the server window will be hidden on system tray, you need to double click to show the window again.
DebugFlags = 3   ; 0=None, 1=Errors, 2=Warnings, 3=Errors+Warnings, 4=Infos, 7=All

[System]
UpdateMode = 1
BufferLength = 512
NumBuffers = 4

[Modules]
EnableVehicles = 1
EnableAmbient = 1


[Vehicles]
Volume = 0.6
VolumeNPCsMult = 0.9
MaxDistance = 200.0

EnableOnCars = 1
EnableOnBikes = 1
EnableOnPlanes = 1
EnableOnHelis = 1
EnableOnBoats = 1

RPMmode = 0   ; 0 = Sport (high), 1 = Road (low)
UseBackfireForAll = 0   ; Set 1 if you want all supported vehicles using backfire by default


[Ambient]
Volume = 1.0
TrafficVolume = 0.7
CrowdVolume = 0.7
WindAmbience = 0.2
ReplaceRain = 1

