[Config]

;Show text when changing speed/acceleration
ShowText = 1

;You can change this at anytime in-game
LockAccel = 0

;Default values for the game start and default command
DefAccel = 0.015
DefDecel = 0.007

[Commands]

Mode1      =orb1
Mode2      =orb2
Mode3      =orb3
Deactivate =orb4
Modifier = 17

[CameraOffset]

;Horizontal & X offset
X+ = 99
X- = 97

;Zoom & Y offset
Y+ = 102
Y- = 100

;Vertical & Z offset
Z+ = 107
Z- = 109

Rotation+ = 105
Rotation- = 103

IncreaseSpeed = 57
DecreaseSpeed = 56