# Improved Jetpack Control Mod by Junior_Djjr - MixMods.com.br
[Settings]
THRUST_FULL = 4.0           # (0.6) Velocidade de aceleração.
THRUST_STRAFE = 2.0         # (0.3) Velocidade de aceleração para o lado.
THRUST_ANTIGRAVITY = 0.001  # (0.008) Força contra a gravidade quando acelera. Números menores têm mais gravidade.
LEG_SWING_DAMP_FRAC = 0.8   # (0.98) Sensibilidade de movimento das pernas. Recomendado abaixar conforme aumenta aceleração.
THRUST_NOMINAL = 1.0        # (0.8) Freio constante.
BRAKE_DIV = -0.5            # (0.5) Divisão de freio. Quanto menos, mais freio. Aceita valores negativos.
