;--------------------------------
; Arquivo de configuração para o mod Ped Spawn Creator por Junior_Djjr - MixMods.com.br
;
; Se você criar algum .ini como mod, NÃO libere o mod completo, em vez disso, compartilhe só o arquivo .ini, pois este mod ainda será atualizado no futuro, e o .ini antigo ainda será compatível.
;
; Use algum mod para pegar a coord (posição) e ângulo no jogo, por exemplo: https://www.mixmods.com.br/2018/04/coords-angle-copiar-coordenadas-e-angulo-do-cj/
; Use Cheat Menu by Grinch_ ou Anim Manager by Ryosuke839 para encontrar animações.
; Use algum site ou mod para encontrar o modelo do ped. Use -1 para aleatório.
;
; Configurado por: (seu nome)
;--------------------------------

[Settings]
TestMode = 0  ; 1 = teleportar pro local; 2 = teleportar e 100% de chance.
AreaID = 11  ; Usando o test mode, digite AREAID como um cheat para mostrar o ID da área atual.
SpawnOnMission = 1
; Posição de ativação:
Coord = 503.5464 -73.9139 998.7651
Radius = 30.0  ; Distância em metros

[Ped1]
Chance = 100
Model = -1
Coord = 511.2542 -69.6515 998.8
Angle = 90
FixGround = 1
Freeze = 1
Collision = 0
AnimIFP = PED
Anim = SEAT_idle

[Ped2]
Chance = 75
Model = -1
Coord = 510.2744 -68.5533 998.7578
Angle = 180
FixGround = 1
Freeze = 1
Collision = 1
AnimIFP = MISC
Anim = Seat_talk_01

[Ped3]
Chance = 60
Model = -1
Coord = 505.7081 -67.9812 997.6
Angle = 0
FixGround = 0
Freeze = 1
Collision = 0
AnimIFP = INT_HOUSE
Anim = BED_Loop_R

[Ped4]
Chance = 75
Model = -1
Coord = 495.4035 -72.2 997.75
Angle = 180
FixGround = 0
Freeze = 1
Collision = 0
AnimIFP = INT_HOUSE
Anim = LOU_Loop

[Ped5]
Chance = 75
Model = -1
Coord = 505.0 -78.4958 998.9609
Angle = 0
FixGround = 1
Freeze = 1
Collision = 1
AnimIFP = MISC
Anim = Plyrlean_loop

[Ped6]
Chance = 50
Model = 50 ; WMYMECH (mechanic)
Coord = 507.9386 -88.528 998.9609
Angle = 145
FixGround = 1
Freeze = 1
Collision = 1
AnimIFP = COP_AMBIENT
Anim = Copbrowse_loop

[Ped7]
Chance = 75
Model = -1
Coord = 488.6 -73.7198 998.8
Angle = 270
FixGround = 1
Freeze = 1
Collision = 0
AnimIFP = PED
Anim = SEAT_idle

