; Anim Menu by Wirmaple73
; Version 1.1

; Choose the (virtual key) activation keys for the menu,
; by default, 'LALT + M' will be used to open the menu in case this file is missing or invalid.

[Controls]
ActivationKey1 = 18
ActivationKey2 = 77